Parameters:
  preprocess:
    label: False
    subset: True
    split: True
  compression_type: png # PNG, JPEG, TIFF
  concatenation:
    concatenation_type: interleaved # interleaved, NCD_shuffle, np_concat
    concatenation_axis: 0 # for classic/np_concat
  kfold_nr: 5
  dataset: 1
  multiclassification: False
  class1 : 'dalmatian'
  class2 : 'camera'
General:
  kfold_iterations:
    - 0
    - 1
    - 2
    - 3
    - 4