Parameters:
  preprocess:
    label: True
    subset: True
    split: True
  feature_extration:
    rotation_ncd: True
  ncd_baseline:
    ncd_type : PNG
  compression_type: PNG # PNG, JPEG, TIFF
  concatenation:
    concatenation_type: interleaved # interleaved, NCD_shuffle, np_concat
    concatenation_axis: 0
  kfold_nr: 5
  dataset: 1
  multiclassification: False
  class1 : 'camera'
  class2 : 'kangaroo'
General:
  kfold_iterations:
    - 0
    - 1
    - 2
    - 3
    - 4