class1: dalmatian
class2: camera
compression_type: png
concatenation:
  concatenation_axis: 0
  concatenation_type: interleaved
dataset: 1
kfold_nr: 5
multiclassification: false
preprocess:
  label: false
  split: true
  subset: true
