class1: camera
class2: kangaroo
dataset: 1
feature_extration:
  rotation_ncd: true
kfold_nr: 5
multiclassification: false
ncd_baseline:
  ncd_type: jpeg_compressionVertical
preprocess:
  label: true
  split: true
  subset: true
