Parameters:
  preprocess:
    label: True
    subset: True
    split: True
  feature_extration:
    rotation_ncd: True
  ncd_baseline:
    ncd_type : jpeg_compression
  kfold_nr: 5
  dataset: 1
  multiclassification: False
  class1 : 'kangaroo'
  class2 : 'pigeon'
General:
  kfold_iterations:
    - 0
    - 1
    - 2
    - 3
    - 4